events {}

http {
    upstream apps {
        server app1:5000 max_fails=3 fail_timeout=5s;
        server app2:5000 max_fails=3 fail_timeout=5s;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://apps;
            proxy_next_upstream error timeout http_502 http_503 http_504;
        }
    }
}
